-- MySQL Script generated by MySQL Workbench
-- 11/29/16 09:19:40
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema test
-- -----------------------------------------------------
CREATE DATABASE IF NOT EXISTS `test`;
-- -----------------------------------------------------
-- Schema test
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `test` DEFAULT CHARACTER SET utf8 ;
USE `test` ;

-- -----------------------------------------------------
-- Table `test`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`Usuario` (
  `username` VARCHAR(15) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `permiso` TINYINT(1) NOT NULL,
  PRIMARY KEY (`username`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test`.`Encuestado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`Encuestado` (
  `telefono` VARCHAR(45) NOT NULL,
  `rut` VARCHAR(15) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`telefono`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test`.`Llamada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`Llamada` (
  `idLlamada` INT NOT NULL AUTO_INCREMENT,
  `observaciones` VARCHAR(45) NULL,
  `username` VARCHAR(15) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idLlamada`),
  INDEX `fk_Llamada_Usuario1_idx` (`username` ASC),
  INDEX `fk_Llamada_Encuestado1_idx` (`telefono` ASC),
  CONSTRAINT `fk_Llamada_Usuario1`
    FOREIGN KEY (`username`)
    REFERENCES `test`.`Usuario` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Llamada_Encuestado1`
    FOREIGN KEY (`telefono`)
    REFERENCES `test`.`Encuestado` (`telefono`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test`.`Proyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`Proyecto` (
  `idProyecto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `link` VARCHAR(45) NOT NULL,
  `activo` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`idProyecto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test`.`Encuestado-Proyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test`.`Encuestado-Proyecto` (
  `idProyecto` INT NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idProyecto`, `telefono`),
  INDEX `fk_Proyecto_has_Encuestado_Encuestado1_idx` (`telefono` ASC),
  INDEX `fk_Proyecto_has_Encuestado_Proyecto1_idx` (`idProyecto` ASC),
  CONSTRAINT `fk_Proyecto_has_Encuestado_Proyecto1`
    FOREIGN KEY (`idProyecto`)
    REFERENCES `test`.`Proyecto` (`idProyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Proyecto_has_Encuestado_Encuestado1`
    FOREIGN KEY (`telefono`)
    REFERENCES `test`.`Encuestado` (`telefono`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;